# Development dependencies only.
name: minutes

channels:
    - conda-forge
dependencies:
    - python=3.6
    - scipy=0.19.1
    - keras=2.1.3
    - tensorflow=1.6.0
    - scikit-learn=0.19.1
    - pytest
    - pytest-cov
    - pip:
        - flake8
