# Development dependencies only.
name: minutes

channels:
    - conda-forge
dependencies:
    - python=3.6
    - scipy=0.19.1
    - keras=2.0.9
    - librosa=0.6.0
    - matplotlib=2.2.0
    - scikit-learn=0.19.1
    - pytest
    - pytest-cov
    - pip:
        - python_speech_features
