name: minutes

channels:
    - conda-forge
dependencies:
    - python=3.6
    - flask=0.12.2
    - lxml=4.1.0
    - scipy=0.19.1
    - requests=2.18.4
    - keras=2.0.9
    - h5py=2.7.1
    - librosa=0.6.0
    - matplotlib=2.2.0
    - youtube-dl
    - scikit-learn=0.19.1
    - pip:
        - python_speech_features
